name = "deepseek-api-proxy"
main = "src/worker.js"
compatibility_date = "2023-12-01"

[env.production.vars]
ENVIRONMENT = "production"

# 在Cloudflare Dashboard中设置环境变量:
# DEEPSEEK_API_KEY = "your-deepseek-api-key"

[[env.production.routes]]
pattern = "your-domain.com/api/*"
zone_name = "your-domain.com"

[build]
command = ""

[build.upload]
format = "service-worker"