name = "bazi-backend"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB"
database_name = "wishing-pool-db"
database_id = "4a466de5-8906-4cd7-a17f-ac48c57c150c"

[[routes]]
pattern = "api.mybazi.net/*"
zone_name = "mybazi.net"

[vars]
# SENDINBLUE_API_KEY - 已移至 Cloudflare 环境变量/Secret 管理
RESET_URL_BASE = "https://mybazi.net/system/reset.html"
# JWT_SECRET - 已移至 Cloudflare 环境变量/Secret 管理
# DEEPSEEK_API_KEY - 已移至 Cloudflare 环境变量/Secret 管理
ENVIRONMENT = "production"